### ISSUE TITLE
How to create labels layer 'Cluster IDs in Space'?

### ISSUE THREAD

**Issue by Michael-shannon** [BiAPoL/napari-clusters-plotter#27] opened 2021-12-03 15:07 UTC
Hiya

Great tool and really easy to use - thank you.

I couldn't quite understand how to create the new labels layer called 'cluster_IDs_in_space' that you have in the readme. After completing the UMAP and K-means, I can get a plot of UMAP0 vs UMAP1, on which I can draw clusters, and can view my originally segmented image on top of the raw one, but I am stuck creating this new layer required to translate from UMAP to real space.

Is it simple to create within napari GUI?

Most appreciatively,

Michael

**Comment by lazigu** [comment] 2021-12-03 17:52
Hi, Michael!

I'm happy to hear that you tried out the plugin and it was easy to use so far!

Regarding the 'cluster_IDs_in_space' layer, it is generated automatically, when you select UMAP_1 and UMAP_0 as axes and select KMEANS_CLUSTER_ID in the "CLustering" field.

![image](https://user-images.githubusercontent.com/52177660/144647039-3df9cd68-471c-4322-8616-603e25d34795.png)

Then after you click Run button, you should see the plot, and also a new layer 'cluster_IDs_in_space'.
If you did these steps but no new layer is generated for you, did you maybe get some kind of error that I could try reproducing? I just tried out the latest version again, and from my side, it was working as expected.
Even if you do not do any dimensionality reduction (UMAP) or use KMeans clustering, but just plot, as an example, area against the mean intensity, after clicking Run button and manually selecting a region in the plot, you should automatically see a new layer generated (turn off original layers visibility for a better clusters visibility because the opacity of  'cluster_IDs_in_space' layer is not 100%).

![image](https://user-images.githubusercontent.com/52177660/144649481-2d1e23f4-90b7-40d0-b922-8081ce1a9ab9.png)

Please tell me how it goes! If it still does not work, It might be some kind of bug and I will do my best to find out what happened :)

Best wishes,
Laura

**Comment by lazigu** [comment] 2022-01-20 17:18
Hi Michael @Michael-shannon, any follow up on this? We changed a bit how the 'Cluster IDs in space' layer is generated in newer releases, so maybe you have tried that?
Otherwise, I would close this issue :)

Best wishes,
Laura

**Closed** 2022-01-31 10:12 UTC
Labels: question
